[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = 10  # ✅ Max allowed on free tier
  external_node_modules = ["busboy", "openai", "@netlify/functions"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-File-Name"

[dev]
  framework = "vite"         # ✅ You are using Vite, not CRA
  targetPort = 5173          # ✅ Vite default port
  functionsPort = 9999
  autoLaunch = true
